services:
  - type: web
    name: uba-backend
    env: python
    rootDirectory: app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app/__init__.py
      - key: FLASK_ENV
        value: production
    plan: free
