services:
  - type: web
    name: uba-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: backend/wsgi.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    plan: free
